name: Linear Programming With Around Searching
config:
  n_checks_max : 10000
  stop_if_sol_found : True

  # The search method to use, either random or random_without_replacement
  search_method : random_without_replacement