name: VM Placement Splittable
config:
  n_servers : 10
  n_vms : 20
  n_servers_solution : 6
  ressources:
    cpu:
      vm_distribution: uniform
      vm_max: 128
      vm_min: 64
    memory:
      vm_distribution: uniform
      vm_max: 32
      vm_min: 4
    disk:
      vm_distribution: uniform
      vm_max : 4000
      vm_min : 1000
  capacity_bonus_servers_solution_frac: 0.1
  capacity_malus_other_servers_frac: 0.9
  relax_unique_assignment_constraint: False
  verbose : 1

  # Splittability parameters
  splittable: True
  n_servers_splittable_max : 3
  proportion_splittable_min : 0