name: VM Placement with Incompatibilities
config:
  n_servers : 5
  n_vms : 10
  n_servers_solution : 4
  ressources:
    cpu:
      vm_distribution: uniform
      vm_max: 128
      vm_min: 64
    memory:
      vm_distribution: uniform
      vm_max: 32
      vm_min: 4
    disk:
      vm_distribution: uniform
      vm_max : 4000
      vm_min : 1000
  capacity_bonus_servers_solution_frac: 0.1
  capacity_malus_other_servers_frac: 0.9
  relax_unique_assignment_constraint: False
  verbose : 1

  # VM incompatibilities config
  incomp_vm_indexes :

    # - [0, 1, 2]
    - [2, 3]
    # - [4, 5]
    # - [6, 7]
    # - [8, 9]
    # - [10, 11]
    # - [0, 2, 4, 7]
    # - [1, 3, 5, 6]
