name: VM Placement Empty Servers
config:
  n_servers : 5
  n_vms : 10
  n_servers_solution : 4
  ressources:
    cpu:
      vm_distribution: uniform
      vm_max: 128
      vm_min: 64
    memory:
      vm_distribution: uniform
      vm_max: 32
      vm_min: 4
    disk:
      vm_distribution: uniform
      vm_max : 4000
      vm_min : 1000
  capacity_bonus_servers_solution_frac: 0
  capacity_malus_other_servers_frac: 0
  relax_unique_assignment_constraint: False
  verbose : 1