# Hyperparameters
max_runtime_seconds : 60
n_iterations_max : inf

# Logging
do_wandb : True
wandb_config:
  project : operational_research
do_tb : True
do_cli : True
do_tqdm : False


# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - algo : pyo
  - problem : vmp
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .