# Hyperparameters
max_time_seconds : 60
n_iterations_max : inf

# Logging
do_wandb : False
wandb_config:
  project : wandb_project_example
  entity : wandb_entity_example
do_tb : True
do_cli : True
do_tqdm : True


# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - algo : lp_around
  - problem : vmp
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .